openapi: 3.0.0
info:
  title: Sample API
  description: |
    Optional multiline
    description
  version: 0.0.0

paths:
  /users:
    get:
      summary: Return stuff
      responses:
        '200':
          description: A JSON object